# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: acossari <acossari@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/04/24 16:21:57 by acossari          #+#    #+#              #
#    Updated: 2025/04/24 18:09:21 by acossari         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Name of the static library to create
NAME	=	libft.a

# Compiler to use (cc is the standard compiler at 42)
CC	=	cc

# Compiler flags:
#   -Wall   : enable all warnings
#   -Wextra : enable extra warnings
#   -Werror : treat warnings as errors
CFLAGS	=	-Wall -Wextra -Werror

# List of source files (.c)
SRCS	=	ft_isalpha.c	ft_isdigit.c	ft_isalnum.c	ft_isascii.c	\
	ft_isprint.c	ft_strlen.c	ft_memset.c	ft_bzero.c	\
	ft_memcpy.c	ft_memmove.c	ft_strlcpy.c	ft_strlcat.c	\
	ft_toupper.c	ft_tolower.c	ft_strchr.c	ft_strrchr.c	\
	ft_strncmp.c	ft_memchr.c	ft_memcmp.c	ft_strnstr.c	\
	ft_atoi.c	ft_calloc.c	ft_strdup.c	ft_substr.c	\
	ft_strjoin.c	ft_strtrim.c	ft_split.c	ft_itoa.c	\
	ft_strmapi.c	ft_striteri.c	ft_putchar_fd.c	ft_putstr_fd.c	\
	ft_putendl_fd.c	ft_putnbr_fd.c

# Object files (.o) generated by replacing .c extensions in SRCS
OBJS	=	$(SRCS:.c=.o)

# Default target: builds the library when you run `make`
all:	$(NAME)

# Rule to create the library archive from object files
# $@ is the target (libft.a), $^ are all prerequisites (the .o files)
$(NAME):	$(OBJS)
	ar rcs $@ $^

# Pattern rule: compile any .c into corresponding .o
# $< is the first prerequisite (the .c file), $@ is the target (.o file)
%.o:	%.c libft.h
	$(CC) $(CFLAGS) -c $< -o $@

# Remove all object files
clean:
	rm -f $(OBJS)

# Remove object files and the library
fclean:	clean
	rm -f $(NAME)

# Rebuild everything from scratch
re:	fclean all

# Declare these targets as phony (not real files)
.PHONY:	all clean fclean re
